# YOUR NAME OR TITLE OF YOUR SITE
name: Enrique Munoz de Cote

# YOUR BRAND/PERSONAL TAGLINE
tagline: AI entrepreneur/computer scientist/engineer | creating the next AI venture

# YOUR/BRAND IMAGE URL
Image_URL: /assets/images/enrique.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: enriquedecote
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # FACEBOOK
  - Name: Facebook
    URL:
    Username: harsh98trivedi
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL:
    Username: harsh98trivedi
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # SCHOLAR
  - Name: Google Scholar
    URL: https://scholar.google.com.mx/citations?user=GCvqGG4AAAAJ&hl=en
    # Username: 'harshtrivedi'
    Color: '#ee9b00'
    # Text_Color: '#000000'
    Icon-Class: fab fa-scholar

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: enriquedecote
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # MEDIUM
  - Name: Medium
    URL: https://enriquedecote.medium.com
    Username: 
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'


    # CLUBHOUSE
  - Name: Clubhouse
    URL:
    Username: '@harsh98trivedi'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    

    # YOUTUBE
  - Name: YouTube
    URL:
    Username: UCS3zvA_2r1iGT7MB3NVCGAw
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: https://github.com
    Username: enriquedecote
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: mailto:enrique@people-ai.com
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL:
    Username: harsh98trivedi
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # VIMEO
  - Name: Vimeo
    URL:
    Username: harshtrivedi
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL:
    Username: theharshtrivedi
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL:
    Username: harshtrivedi
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL:
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL:
    Username: theharshtrivedi
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  - Name: Snapchat
    URL:
    Username: 'harsh98trivedi'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost


  #   # DISCORD
  # - Name: Discord
  #   URL:
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL:
    Username: 'harsh98trivedi'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

    # BEHANCE
  - Name: Behance
    URL:
    Username: harsh98trivedi
    Color: '#1769ff'
    Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL:
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - Name: DeviantArt
    URL:
    Username: harshtrivedi
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

    # FIGMA
  - Name: Figma
    URL:
    Username: '@harshtrivedi'
    Icon-Class: fab fa-figma
    Color: '#ff2865'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL:
    Username: 314ihryk3edvtusti6il3oy3x5da
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL:
    Username: harsh98trivedi
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL:
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok


    # DEV.TO
  - Name: Dev.to
    URL:
    Username: harsh98trivedi
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL:
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL:
    Username: harshtrivedi
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

  - Name: Links
    URL:
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

ventures:
  - Name: Single cell biotechnology
    URL: https://www.cellclar.com/
    Timeframe: Feb 2024
    Description: We specialise in single cell omics data analysis leading to insights & novel target discoveries
    Logo: /assets/images/cellclar.svg
    Color: white
    Role: Vice president of AI

  - Name: AI marketing and growth services
    URL: https://www.hypergrowth.io/
    Timeframe: Nov 2022
    Description: Data-driven growth acceleration network and services connecting the tech industry (startups, scale-ups, enterprise and government) with people, processes and data. We design and implement processes based on proven frameworks. Now we're using AI and machine learning to guide these processes and leverage these technologies in key growth areas such as marketing and decision-support systems.
    Logo: https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/themes/2151226666/settings_images/jRnhPeEVTSeGsEfZie8z_hypergrowth-logo-white.svg.png
    Role: Co-founder

  # - Name: Art marketplace
  #   URL: https://www.atelierdao.xyz/
  #   Timeframe: July 2022 
  #   Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  #   Logo: https://www.atelierdao.xyz/images/Atelier_logo.svg

  # - Name: 'Blockchain and AI venture builder'
  #   URL: https://www.darkmatterventures.io/
  #   Timeframe: Jan 2022
  #   Description: Blockchain and AI venture builder. An R&D lab building products in the intersection between AI and blockchain technologies.
  #   Logo: /assets/images/dmv.svg
  
  - Name: Computer vision & AI for public spaces
    URL: https://geckomatics.com/
    Color: '#edf2f4'
    Timeframe: July 2021 - Oct 2022
    Description: An AI computer vision startup founded to solve the scarcity of high quality, recent geographic information. Geckomatics has redesigned how outdoor mobile mapping is done. Using a 360ยบ camera that you can mount on any vehicle, our deep learning algorithms recognize objects and put them on a map.
    Logo: /assets/images/geckomatics.png
    Role: co-founder, CTO

  - Name: 'Deep tech consultancy in AI & Machine Learning'
    URL: https://people-ai.com/
    Timeframe: July 2020 
    Description: AI solutions for tier-1 VC backed startups, enterprise, and government. Based in Cambridge, UK, what distinguish us is our thrive to solve deep technical data problems.
    Logo: '/assets/images/pnai_horizontal.png'
    Role: Founder

experience:
  - Name: Secondmind
    URL: https://www.secondmind.ai/
    Timeframe: Oct 2016 - Jan 2020
    Role: Director of ML
    Description:  An ML startup with the mission of empowering people in business to make better decisions. Backed by more than four years of practical, award-winning artificial intelligence (AI) and machine learning (ML) research, Secondmind is closing the gap between people and AI with easy-to-use and understand ML technology, designed to help businesses better predict, plan, compete and manage risk in an increasingly uncertain world. The company has been developing Secondmind for four years under the name PROWLER.io.
    Logo: /assets/images/Secondmind.webp
    Color: white  
# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown

google_analytics: G-1ZF32FQLQM

plugins:
  - jekyll-seo-tag